export const ADD_MEMBER_REQUEST = "ADD_MEMBER_REQUEST";
export const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS";
export const ADD_MEMBER_FAILED = "ADD_MEMBER_FAILED";

export const GET_MEMBER_REQUEST = "GET_MEMBER_REQUEST";
export const GET_MEMBER_SUCCESS = "GET_MEMBER_SUCCESS";
export const GET_MEMBER_FAILED = "GET_MEMBER_FAILED";

export const DELET_MEMBER_REQUEST = "DELET_MEMBER_REQUEST";
export const DELET_MEMBER_SUCCESS = "DELET_MEMBER_SUCCESS";
export const DELET_MEMBER_FAILED =  "DELET_MEMBER_FAILED";
